"""This module defines constants for RAC1 locations"""


class RAC1LOCATION:
    """String constants for RAC1 locations"""
    NOVALIS_PLUMBER = "Novalis: Plumber"
    NOVALIS_CHAIRMAN = "Novalis: Chairman"
    ARIDIA_HOVERBOARD = "Aridia: Kill the Sand Sharks"
    ARIDIA_TRESPASSER = "Aridia: Construction Zone"
    ARIDIA_SONIC_SUMMONER = "Aridia: Bring Zoomerator to Agent"
    KERWAN_SWINGSHOT = "Kerwan: Fitness Course"
    KERWAN_HELIPACK = "Kerwan: Al's Roboshack"
    KERWAN_TRAIN_INFOBOT = "Kerwan: Ride the Robot Train"
    EUDORA_HENCHMAN = "Eudora: Robot Lieutenant"
    EUDORA_SUCK_CANNON = "Eudora: Explore the Mills"
    RILGAR_QUARK_INFOBOT = "Rilgar: Locate Captain Quark"
    RILGAR_PLATINUM_ZOOMERATOR = "Rilgar: Win the hoverboard race"
    BLARG_HYDRODISPLACER = "Blarg: Outside as Clank"
    BLARG_EXPLOSION_INFOBOT = "Blarg: Destroy the Warship"
    BLARG_GRINDBOOTS = "Blarg: Explore the Space Station"
    UMBRIS_SNAGGLEBEAST_INFOBOT = "Umbris: Defeat the Snagglebeast"
    BATALIA_GRINDRAIL_INFOBOT = "Batalia: Ride the grindrail"
    BATALIA_COMMANDER_INFOBOT = "Batalia: Commando"
    BATALIA_METAL_DETECTOR = "Batalia: Shoot down the Bombers"
    GASPAR_PILOT_HELMET = "Gaspar: Get the pilot helmet"
    ORXON_CLANK_INFOBOT = "Orxon: Clank: Traverse the Wilderness"
    ORXON_RATCHET_INFOBOT = "Orxon: Chase the Infobot"
    ORXON_CLANK_MAGNEBOOTS = "Orxon: Clank: Search the Labs"
    POKITARU_O2_MASK = "Pokitaru: Pilot the Ship"
    POKITARU_SEWER_PERSUADER = "Pokitaru: Trade Raritanium"
    POKITARU_THRUSTER_PACK = "Pokitaru: Bob's Shop"
    HOVEN_TURRET_INFOBOT = "Hoven: Destroy the Planet-buster"
    HOVEN_HYDRO_PACK = "Hoven: Edwina's Shop"
    HOVEN_RARITANIUM = "Hoven: Talk to the Miner"
    GEMLIK_QUARK_FIGHT = "Gemlik: Defeat Captain Quark"
    OLTANIS_INFOBOT = "Oltanis: Grindrail path: Scrap Merchant"
    OLTANIS_PDA = "Oltanis: Magneboot path: Buy the PDA from Steve"
    OLTANIS_MORPH_O_RAY = "Oltanis: Swingshot path: Search the city"
    QUARTU_GIANT_CLANK_INFOBOT = "Quartu: Giant Clank Fight"
    QUARTU_BOLT_GRABBER = "Quartu: Water Path"
    QUARTU_INFILTRATE_INFOBOT = "Quartu: Clank's mother"
    KALEBO_HOLOGUISE = "Kalebo III: Win the hoverboard race"
    KALEBO_MAP_O_MATIC = "Kalebo III: Grindrail: Helpdesk"
    FLEET_INFOBOT = "Drek's Fleet: Flagship"
    FLEET_CODEBOT = "Drek's Fleet: Water section"
    VELDIN_DREK = "Veldin: Defeat Chairman Drek"
