"""This module defines constants for RAC1 Gold Bolt locations"""


class RAC1BOLT:
    """String constants for RAC1 Gold Bolt locations"""
    NOVALIS_WATERWORKS = "Novalis: Gold Bolt: Waterworks"
    NOVALIS_CAVES = "Novalis: Gold Bolt: Caves"
    NOVALIS_AMOEBOID = "Novalis: Gold Bolt: Amoeboid Caves"
    ARIDIA_TRESPASSER = "Aridia: Gold Bolt: Construction Zone"
    ARIDIA_ISLAND = "Aridia: Gold bolt: Island"
    ARIDIA_MAGNEBOOTS = "Aridia: Gold Bolt: Laser"
    ARIDIA_SANDSHARK = "Aridia: Gold bolt: Sandshark Cave"
    KERWAN_BELOW_SHIP = "Kerwan: Gold Bolt: Underpass"
    KERWAN_TRAIN_STATION = "Kerwan: Gold Bolt: Train Station"
    KERWAN_LONE_TOWER = "Kerwan: Gold Bolt: Fitness Course Tower"
    EUDORA = "Eudora: Gold Bolt"
    RILGAR_MAZE = "Rilgar: Gold Bolt: Maze"
    RILGAR_WATERWORKS = "Rilgar: Gold Bolt: Sewer Cave"
    BLARG_OUTSIDE = "Blarg: Gold Bolt: Outside"
    BLARG_SWARMER = "Blarg: Gold Bolt: Cages"
    UMBRIS_PRESSURE_PUZZLE = "Umbris: Gold Bolt: Lighthouse puzzle"
    UMBRIS_JUMP_DOWN = "Umbris: Gold bolt: Jumping Down"
    BATALIA_CLIFFSIDE = "Batalia: Gold Bolt: Cliffside"
    BATALIA_TRESPASSER = "Batalia: Gold Bolt: House Roof"
    GASPAR_SWINGSHOT = "Gaspar: Gold Bolt: Destroy the Bombers"
    GASPAR_VOLCANO = "Gaspar: Gold Bolt: Volcano"
    ORXON_CLANK = "Orxon: Gold Bolt: Return to the Clank section"
    ORXON_VISIBOMB = "Orxon: Gold Bolt: Long Tunnel"
    POKITARU = "Pokitaru: Gold Bolt: Waterfalls"
    HOVEN_WATER = "Hoven: Gold Bolt: in the Water Cave"
    HOVEN_WALLJUMP = "Hoven: Gold Bolt: Moving wall jump"
    GEMLIK = "Gemlik: Gold Bolt: Visibomb Hidden Tower"
    OLTANIS_MAIN = "Oltanis: Gold Bolt: Grindrail path: Swingshot Upper Ledge"
    OLTANIS_MAGNET_1 = "Oltanis: Gold Bolt: Magneboot path: Ledge near Bomber"
    OLTANIS_MAGNET_2 = "Oltanis: Gold Bolt: Magneboot path: Ledge hang"
    OLTANIS_FINAL = "Oltanis: Gold Bolt: All Objectives"
    QUARTU_MOM = "Quartu: Gold Bolt: Behind Clank's mother"
    QUARTU_CODEBOT = "Quartu: Gold Bolt: Codebot door"
    KALEBO_GRIND = "Kalebo III: Gold Bolt: On the Grindrail"
    KALEBO_BREAK_ROOM = "Kalebo III: Gold Bolt: Employee break room"
    FLEET_WATER = "Drek's Fleet: Gold Bolt: Water section"
    FLEET_ROBOT = "Drek's Fleet: Gold Bolt: Sidepath with robot guards"
    VELDIN_TAUNTER = "Veldin: Gold Bolt: Taunter the horny toad"
    VELDIN_HALFWAY = "Veldin: Gold Bolt: Platforms"
    VELDIN_GRIND = "Veldin: Gold Bolt: Grindrail"
