"""This module defines constants for RAC1 planets"""


class RAC1PLANET:
    """String constants for RAC1 planets"""
    GENERAL = "General"
    NOVALIS = "Novalis"
    ARIDIA = "Aridia"
    KERWAN = "Kerwan"
    EUDORA = "Eudora"
    BLARG = "Blarg Station"
    RILGAR = "Rilgar"
    UMBRIS = "Umbris"
    BATALIA = "Batalia"
    ORXON = "Orxon"
    POKITARU = "Pokitaru"
    GASPAR = "Gaspar"
    HOVEN = "Hoven"
    GEMLIK = "Gemlik Base"
    OLTANIS = "Oltanis"
    QUARTU = "Quartu"
    KALEBO = "Kalebo III"
    FLEET = "Drek's Fleet"
    VELDIN = "Veldin"
    MENU = "Menu"
