"""This module defines constants for RAC1 skillpoints"""


class RAC1SKILLPOINT:
    """String constants for RAC1 skillpoints"""
    NOVALIS_TAKE_AIM = "Novalis: Skillpoint: Take Aim"
    ARIDIA_SWING_IT = "Aridia: Skillpoint: Swing it!"
    ARIDIA_TRANSPORTED = "Aridia: Skillpoint: Transported"
    KERWAN_STRIKE_A_POSE = "Kerwan: Skillpoint: Strike a pose"
    KERWAN_BLIMPY = "Kerwan: Skillpoint: Blimpy"
    KERWAN_QWARKTASTIC = "Kerwan: Skillpoint: Qwarktastic"
    EUDORA_ANY_TEN = "Eudora: Skillpoint: Any Ten"
    GENERAL_TRICKY = "Hoverboard: Skillpoint: Tricky"
    RILGAR_CLUCK_CLUCK = "Rilgar: Skillpoint: Cluck, Cluck"
    RILGAR_SPEEDY = "Rilgar: Skillpoint: Speedy"
    BLARG_GIRL_TROUBLE = "Blarg Station: Skillpoint: Girl Trouble"
    BATALIA_JUMPER = "Batalia: Skillpoint: Jumper"
    BATALIA_ACCURACY_COUNTS = "Batalia: Skillpoint: Accuracy Counts"
    BATALIA_EAT_LEAD = "Batalia: Skillpoint: Eat Lead"
    GASPAR_DESTROYED = "Gaspar: Skillpoint: Destroyed"
    GASPAR_GUNNER = "Gaspar: Skillpoint: Gunner"
    ORXON_SNIPER = "Orxon: Skillpoint: Sniper"
    ORXON_HEY_OVER_HERE = "Orxon: Skillpoint: Hey, Over Here!"
    POKITARU_ALIEN_INVASION = "Pokitaru: Skillpoint: Alien Invasion"
    POKITARU_BURIED_TREASURE = "Pokitaru: Skillpoint: Buried Treasure"
    HOVEN_PEST_CONTROL = "Hoven: Skillpoint: Pest Control"
    HOVEN_WHIRLYBIRDS = "Hoven: Skillpoint: Whirlybirds"
    GEMLIK_SITTING_DUCKS = "Gemlik Base: Skillpoint: Sitting Ducks"
    OLTANIS_SHATTERED_GLASS = "Oltanis: Skillpoint: Shattered Glass"
    OLTANIS_BLAST_EM = "Oltanis: Skillpoint: Blast Em!"
    KALEBO_HEAVY_TRAFFIC = "Kalebo III: Skillpoint: Heavy Traffic"
    KALEBO_MAGICIAN = "Kalebo III: Skillpoint: Magician"
    FLEET_SNEAKY = "Drek's Fleet: Skillpoint: Sneaky"
    FLEET_CAREFUL_CRUISE = "Drek's Fleet: Skillpoint: Careful Cruise"
    VELDIN_GOING_COMMANDO = "Veldin: Skillpoint: Going Commando"
