"""This module defines constants for RAC1 weapon vendors"""


class RAC1VENDOR:
    """String constants for RAC1 weapon vendors"""
    NOVALIS_PYROCITOR = "Novalis: Vendor - 2,500"
    NOVALIS_GOLD1 = "Novalis: Golden Weapon 1 - 60,000"
    NOVALIS_GOLD2 = "Novalis: Golden Weapon 2 - 20,000"
    NOVALIS_GOLD3 = "Novalis: Golden Weapon 3 - 60,000"
    NOVALIS_GOLD4 = "Novalis: Golden Weapon 4 - 30,000"
    NOVALIS_GOLD5 = "Novalis: Golden Weapon 5 - 10,000"
    NOVALIS_GOLD6 = "Novalis: Golden Weapon 6 - 20,000"
    NOVALIS_GOLD7 = "Novalis: Golden Weapon 7 - 20,000"
    NOVALIS_GOLD8 = "Novalis: Golden Weapon 8 - 10,000"
    NOVALIS_GOLD9 = "Novalis: Golden Weapon 9 - 10,000"
    NOVALIS_GOLD10 = "Novalis: Golden Weapon 10 - 10,000"
    KERWAN_BLASTER = "Kerwan: Vendor - 2,500"
    EUDORA_GLOVE_OF_DOOM = "Eudora: Vendor - 7,500"
    RILGAR_MINE_GLOVE = "Rilgar: Vendor - 7,500"
    RILGAR_RYNO = "Rilgar: Shady Salesman - 150,000"
    BLARG_TAUNTER = "Blarg: Vendor - 2,500"
    BATALIA_DEVASTATOR = "Batalia: Vendor - 10,000"
    GASPAR_WALLOPER = "Gaspar: Vendor - 7,500"
    ORXON_PREMIUM_NANOTECH = "Orxon: Buy the premium nanotech - 4,000"
    ORXON_ULTRA_NANOTECH = "Orxon: Buy the ultra nanotech - 30,000"
    ORXON_VISIBOMB = "Orxon: Vendor - 15,000"
    POKITARU_DECOY_GLOVE = "Pokitaru: Vendor - 7,500"
    HOVEN_DRONE_DEVICE = "Hoven: Vendor - 7,500"
    OLTANIS_VENDOR_TESLA_CLAW = "Oltanis: Vendor - 40,000"
