"""This module defines constants for RAC1 items"""


class RAC1ITEM:
    """String constants for RAC1 items"""
    VICTORY = "Victory"
    # Weapons
    BOMB_GLOVE = "Bomb Glove"
    PYROCITOR = "Pyrocitor"
    BLASTER = "Blaster"
    GLOVE_OF_DOOM = "Glove of Doom"
    MINE_GLOVE = "Mine Glove"
    TAUNTER = "Taunter"
    SUCK_CANNON = "Suck Cannon"
    DEVASTATOR = "Devastator"
    WALLOPER = "Walloper"
    VISIBOMB = "Visibomb Gun"
    DECOY_GLOVE = "Decoy Glove"
    DRONE_DEVICE = "Drone Device"
    TESLA_CLAW = "Tesla Claw"
    MORPH_O_RAY = "Morph-O-ray"
    RYNO = "R.Y.N.O."
    WRENCH = "Wrench"

    # Gold Weapons
    GOLD_BOMB_GLOVE = "Gold Bomb Glove"
    GOLD_PYROCITOR = "Gold Pyrocitor"
    GOLD_BLASTER = "Gold Blaster"
    GOLD_GLOVE_OF_DOOM = "Gold Glove of Doom"
    GOLD_MINE_GLOVE = "Gold Mine Glove"
    GOLD_SUCK_CANNON = "Gold Suck Cannon"
    GOLD_DEVASTATOR = "Gold Devastator"
    GOLD_DECOY_GLOVE = "Gold Decoy Glove"
    GOLD_TESLA_CLAW = "Gold Tesla Claw"
    GOLD_MORPH_O_RAY = "Gold Morph-o-ray"

    # Gadgets and Items
    TRESPASSER = "Trespasser"
    HYDRODISPLACER = "Hydrodisplacer"
    SWINGSHOT = "Swingshot"
    PDA = "Gadgetron PDA"
    METAL_DETECTOR = "Metal Detector"
    HOLOGUISE = "Hologuise"
    HELI_PACK = "Heli-Pack"
    THRUSTER_PACK = "Thruster-Pack"
    HYDRO_PACK = "Hydro-Pack"
    O2_MASK = "O2 Mask"
    SONIC_SUMMONER = "Sonic Summoner"
    PILOTS_HELMET = "Pilots Helmet"
    GRINDBOOTS = "Grindboots"
    MAGNEBOOTS = "Magneboots"
    HOVERBOARD = "Hoverboard"
    PERSUADER = "Persuader"
    BOLT_GRABBER = "Bolt Grabber"
    PREMIUM_NANOTECH = "Premium Nanotech"
    ULTRA_NANOTECH = "Ultra Nanotech"
    MAP_O_MATIC = "Map-o-matic"
    ZOOMERATOR = "Zoomerator"
    RARITANIUM = "Raritanium"
    CODEBOT = "CodeBot"

    # Progressive items
    PROGRESSIVE_PACK = "Progressive Pack"
    PROGRESSIVE_HELMET = "Progressive Helmet"
    PROGRESSIVE_SUCK = "Progressive Suck Cannon"
    PROGRESSIVE_BOMB = "Progressive Bomb Glove"
    PROGRESSIVE_DEVASTATOR = "Progressive Devastator"
    PROGRESSIVE_BLASTER = "Progressive Blaster"
    PROGRESSIVE_PYROCITOR = "Progressive Pyrocitor"
    PROGRESSIVE_MINE = "Progressive Mine Glove"
    PROGRESSIVE_TESLA = "Progressive Tesla Claw"
    PROGRESSIVE_DOOM = "Progressive Glove of Doom"
    PROGRESSIVE_MORPH = "Progressive Morph-o-ray"
    PROGRESSIVE_DECOY = "Progressive Decoy Glove"
    PROGRESSIVE_BOOT = "Progressive Boots"
    PROGRESSIVE_HOVERBOARD = "Progressive Hoverboard"
    PROGRESSIVE_TRADE = "Progressive Raritanium"
    PROGRESSIVE_NANOTECH = "Progressive Nanotech"

    # Infobots
    VELDIN = "Infobot: Veldin"
    NOVALIS = "Infobot: Novalis"
    ARIDIA = "Infobot: Aridia"
    KERWAN = "Infobot: Kerwan"
    EUDORA = "Infobot: Eudora"
    BLARG = "Infobot: Blarg Station"
    RILGAR = "Infobot: Rilgar"
    UMBRIS = "Infobot: Umbris"
    BATALIA = "Infobot: Batalia"
    ORXON = "Infobot: Orxon"
    GASPAR = "Infobot: Gaspar"
    POKITARU = "Infobot: Pokitaru"
    HOVEN = "Infobot: Hoven"
    GEMLIK = "Infobot: Gemlik Base"
    OLTANIS = "Infobot: Oltanis"
    QUARTU = "Infobot: Quartu"
    KALEBO = "Infobot: Kalebo III"
    FLEET = "Infobot: Drek's Fleet"

    # Gold Bolt Packs
    GOLD_BOLT = "Generic Gold Bolt"
    GOLD_BOLT_1 = "1 Gold Bolt"
    GOLD_BOLT_2 = "2 Gold Bolts"
    GOLD_BOLT_3 = "3 Gold Bolts"
    GOLD_BOLT_4 = "4 Gold Bolts"
    GOLD_BOLT_5 = "5 Gold Bolts"
    GOLD_BOLT_6 = "6 Gold Bolts"
    GOLD_BOLT_7 = "7 Gold Bolts"
    GOLD_BOLT_8 = "8 Gold Bolts"
    GOLD_BOLT_9 = "9 Gold Bolts"
    GOLD_BOLT_10 = "10 Gold Bolts"
    GOLD_BOLT_11 = "11 Gold Bolts"
    GOLD_BOLT_12 = "12 Gold Bolts"
    GOLD_BOLT_13 = "13 Gold Bolts"
    GOLD_BOLT_14 = "14 Gold Bolts"
    GOLD_BOLT_15 = "15 Gold Bolts"
    GOLD_BOLT_16 = "16 Gold Bolts"
    GOLD_BOLT_17 = "17 Gold Bolts"
    GOLD_BOLT_18 = "18 Gold Bolts"
    GOLD_BOLT_19 = "19 Gold Bolts"
    GOLD_BOLT_20 = "20 Gold Bolts"
    GOLD_BOLT_21 = "21 Gold Bolts"
    GOLD_BOLT_22 = "22 Gold Bolts"
    GOLD_BOLT_23 = "23 Gold Bolts"
    GOLD_BOLT_24 = "24 Gold Bolts"
    GOLD_BOLT_25 = "25 Gold Bolts"
    GOLD_BOLT_26 = "26 Gold Bolts"
    GOLD_BOLT_27 = "27 Gold Bolts"
    GOLD_BOLT_28 = "28 Gold Bolts"
    GOLD_BOLT_29 = "29 Gold Bolts"
    GOLD_BOLT_30 = "30 Gold Bolts"
    GOLD_BOLT_31 = "31 Gold Bolts"
    GOLD_BOLT_32 = "32 Gold Bolts"
    GOLD_BOLT_33 = "33 Gold Bolts"
    GOLD_BOLT_34 = "34 Gold Bolts"
    GOLD_BOLT_35 = "35 Gold Bolts"
    GOLD_BOLT_36 = "36 Gold Bolts"
    GOLD_BOLT_37 = "37 Gold Bolts"
    GOLD_BOLT_38 = "38 Gold Bolts"
    GOLD_BOLT_39 = "39 Gold Bolts"
    GOLD_BOLT_40 = "40 Gold Bolts"

    # Bolt Packs
    BOLT_PACK_GENERIC = "Generic Bolt Pack"
    BOLT_PACK_0 = "Nothing"
    BOLT_PACK_1 = "A single bolt"
    BOLT_PACK_10 = "10 bolts"
    BOLT_PACK_100 = "100 bolts"
    BOLT_PACK_250 = "250 bolts"
    BOLT_PACK_500 = "500 bolts"
    BOLT_PACK_750 = "750 bolts"
    BOLT_PACK_1000 = "1,000 bolts"
    BOLT_PACK_2000 = "2,000 bolts"
    BOLT_PACK_3000 = "3,000 bolts"
    BOLT_PACK_4000 = "4,000 bolts"
    BOLT_PACK_5000 = "5,000 bolts"
    BOLT_PACK_6000 = "6,000 bolts"
    BOLT_PACK_7000 = "7,000 bolts"
    BOLT_PACK_8000 = "8,000 bolts"
    BOLT_PACK_9000 = "9,000 bolts"
    BOLT_PACK_10000 = "10,000 bolts"
    BOLT_PACK_12500 = "12,500 bolts"
    BOLT_PACK_15000 = "15,000 bolts"
    BOLT_PACK_17500 = "17,500 bolts"
    BOLT_PACK_20000 = "20,000 bolts"
    BOLT_PACK_25000 = "25,000 bolts"
    BOLT_PACK_30000 = "30,000 bolts"
    BOLT_PACK_40000 = "40,000 bolts"
    BOLT_PACK_50000 = "50,000 bolts"
    BOLT_PACK_75000 = "75,000 bolts"
    BOLT_PACK_100000 = "100,000 bolts"

    # Skill points
    TAKE_AIM = "Take Aim: Skill Point"
    SWING_IT = "Swing it!: Skill Point"
    TRANSPORTED = "Transported: Skill Point"
    STRIKE_A_POSE = "Strike a pose: Skill Point"
    BLIMPY = "Blimpy: Skill Point"
    QWARKTASTIC = "Qwarktastic: Skill Point"
    ANY_TEN = "Any Ten: Skill Point"
    TRICKY = "Tricky: Skill Point"
    CLUCK_CLUCK = "Cluck, Cluck: Skill Point"
    SPEEDY = "Speedy: Skill Point"
    GIRL_TROUBLE = "Girl Trouble: Skill Point"
    JUMPER = "Jumper: Skill Point"
    ACCURACY_COUNTS = "Accuracy Counts: Skill Point"
    EAT_LEAD = "Eat Lead: Skill Point"
    DESTROYED = "Destroyed: Skill Point"
    GUNNER = "Gunner: Skill Point"
    SNIPER = "Sniper: Skill Point"
    HEY_OVER_HERE = "Hey, Over Here!: Skill Point"
    ALIEN_INVASION = "Alien Invasion: Skill Point"
    BURIED_TREASURE = "Buried Treasure: Skill Point"
    PEST_CONTROL = "Pest Control: Skill Point"
    WHIRLYBIRDS = "Whirlybirds: Skill Point"
    SITTING_DUCKS = "Sitting Ducks: Skill Point"
    SHATTERED_GLASS = "Shattered Glass: Skill Point"
    BLAST_EM = "Blast Em!: Skill Point"
    HEAVY_TRAFFIC = "Heavy Traffic: Skill Point"
    MAGICIAN = "Magician: Skill Point"
    SNEAKY = "Sneaky: Skill Point"
    CAREFUL_CRUISE = "Careful Cruise: Skill Point"
    GOING_COMMANDO = "Going Commando: Skill Point"
