"""This module defines constants for RAC1 options"""


class RAC1OPTION:
    """String constants for RAC1 options"""
    # Display names
    OPTIONS = "Options"
    GAME_TITLE = "Rac1"
    GAME_TITLE_FULL = "Ratchet and Clank"
    VERSION = "Version"
    VERSION_NUMBER = "0.2.0"
    START_INVENTORY_FROM_POOL = "Start Inventory From Pool"
    STARTING_ITEM = "Starting Item"
    SHUFFLE_STARTING_PLANET = "Shuffle Starting Planet"
    SHUFFLE_WEAPONS = "Shuffle Weapons"
    EARLY_WEAPON = "Early Weapon"
    SHUFFLE_GADGETS = "Shuffle Gadgets"
    SHUFFLE_PACKS = "Shuffle Packs"
    SHUFFLE_HELMETS = "Shuffle Helmets"
    SHUFFLE_BOOTS = "Shuffle Boots"
    SHUFFLE_EXTRA_ITEMS = "Shuffle Extra Items"
    SHUFFLE_GOLD_BOLTS = "Shuffle Gold Bolts"
    GOLD_BOLT_PACK_SIZE = "Gold Bolt Pack Size"
    BOLT_PACK_SIZE = "Bolt Pack Size"
    SHUFFLE_INFOBOTS = "Shuffle Infobots"
    SHUFFLE_GOLD_WEAPONS = "Shuffle Gold Weapons"
    SHUFFLE_SKILLPOINTS = "Shuffle Skillpoints"
    BOLT_MULTIPLIER = "Bolt Multiplier"
    METAL_DETECTOR_MULTIPLIER = "Metal Detector Bolt Multiplier"
    PURCHASING_LOGIC = "Purchasing logic"
    PROGRESSIVE_WEAPONS = "Progressive Weapons"
    PROGRESSIVE_PACKS = "Progressive Packs"
    PROGRESSIVE_HELMETS = "Progressive Helmets"
    PROGRESSIVE_BOOTS = "Progressive Boots"
    PROGRESSIVE_HOVERBOARD = "Progressive Hoverboard"
    PROGRESSIVE_RARITANIUM = "Progressive Raritanium"
    PROGRESSIVE_NANOTECH = "Progressive Nanotech"
