"""This module defines constants for RAC1 slot data constants."""


class RAC1SLOT:
    """String constants for RAC1 slot data constants."""
    DEATHLINK = "death_link"
    STARTING_ITEM = "starting_item"
    STARTING_LOCATION = "starting_location"
    SHUFFLE_WEAPONS = "shuffle_weapons"
    SHUFFLE_GADGETS = "shuffle_gadgets"
    SHUFFLE_PACKS = "shuffle_packs"
    SHUFFLE_HELMETS = "shuffle_helmets"
    SHUFFLE_BOOTS = "shuffle_boots"
    SHUFFLE_EXTRA_ITEMS = "shuffle_extra_items"
    SHUFFLE_GOLD_BOLTS = "shuffle_gold_bolts"
    SHUFFLE_INFOBOTS = "shuffle_infobots"
    SHUFFLE_GOLD_WEAPONS = "shuffle_gold_weapons"
    SHUFFLE_SKILLPOINTS = "shuffle_skill_points"
    GOLD_BOLT_PACK_SIZE = "pack_size_gold_bolts"
    BOLT_PACK_SIZE = "pack_size_bolts"
    METAL_BOLT_MULTIPLIER = "metal_bolt_multiplier"
    BOLT_MULTIPLIER = "enable_bolt_multiplier"
    VENDOR_LOGIC = "vendor_logic"
    PROGRESSIVE_WEAPONS = "progressive_weapons"
    PROGRESSIVE_PACKS = "progressive_packs"
    PROGRESSIVE_HELMETS = "progressive_helmets"
    PROGRESSIVE_BOOTS = "progressive_boots"
    PROGRESSIVE_HOVERBOARD = "progressive_hoverboard"
    PROGRESSIVE_TRADE = "progressive_raritanium"
    PROGRESSIVE_NANOTECH = "progressive_nanotech"

    STARTING_PLANET = "starting_planet"  # used in __init__.py
